---
bibliography: ./_bookdown_files/references.bib
---

# Abstract

Men who have sex with Men (MSM) represent a vulnerable population affected by numerous health conditions. Syndemic theory has been used as a framework to study the health of MSM for nearly 20 years. However, the literature is plagued by a lack of consensus regarding what constitutes a synergy in a syndemic and recent reviews have shown that most of the papers published thus far failed to demonstrate a synergy nor describe the bio-social interaction needed to account for a true syndemic. Moreover, to our knowledge, none of the existing reviews have focused specifically on MSM.

This scoping review aims to fill this gap by mapping in details how syndemic research on MSM was conducted. A systematic database search was conducted between 2020 and 2021 and 115 studies were included. Our findings showed a lack of diversity regarding the location, design, subpopulation and outcomes studied. In addition, the syndemic conditions as well as their measurement were not focused enough to ensure the robustness and reproducibility of the findings. Furthermore, our results support previous reviews showing a lack of empirical data to support disease interaction in syndemic research applied to MSM. Our review offers some important recommendations to help move the field forward in future work and describes some promising methodological advancement.
