---
bibliography: ./_bookdown_files/references.bib
---

# Discussion

The objective of this scoping review was to map the current knowledge on syndemic research applied to MSM. To this end, we analysed 115 articles and found that the literature was both too homogeneous in some aspects while being not focused enough in other aspects. As we will discuss in more depth below, the location, design, subpopulations and outcomes lacked diversity. On the other hand, the syndemic conditions and ways of measurement were not standardised enough to ensure the robustness, reproducibility and comparability of the findings. Furthermore, a substantial part of the literature does not provide empirical data to support one of the core tenets of syndemic theory---namely disease interaction---as has been pointed out in a previous review [@tsai2015].

## Location

The location of the study is an aspect of syndemic literature suffering from too much homogeneity. Indeed `r percent(.North_America_studies/.N_QualQuant)` of studies are conducted in North America alone while all studies conducted in the Global South represent only `r percent(.GlobalSouth_studies/.N_QualQuant)` of our sample.

Three issues arise from this. First, under-representation of the Global South compromises our understanding of the health of MSM living in these countries. Furthermore, as pointed out by [@weaver2020], the screening tool used to assess the presence of a syndemic condition in the Western context may not be efficient in another sociocultural setting, especially regarding mental health. As syndemics are driven by the sociocultural forces of a given place at a given time, these potential biases need to be addressed in order to conduct meaningful research outside Europe and North America.

Moreover, even for studies conducted in Europe and North America, a large portion of the studies conflate data from different cities, counties, states or even countries in order to obtain a sample big enough to conduct statistical analyses. However, geographical variations in syndemic burdens are likely to be missed. Migration of MSM to larger cities is a well-known phenomenon and thought to be an important part of syndemic production among MSM as well as a source of resilience [@stall2007; @Bruce2011]. Differences in the density of gay social venues and peer organisations as well as exposure to discrimination and violence or an easier access to substances need to be taken into account when studying a syndemic. As Shresta et al. suggested, syndemic research needs to incorporate data from spatial epidemiology to better understand the interactions of socioeconomic forces in the physical space and how these forces can influence health [@shrestha2020]. In their paper, they illustrate their framework with a "syringe-based syndemic" of HCV, HIV, and opioid-related deaths in West Virginia and describe how variables related to unique physical space such as local drug availability drove this syndemic.

## Design

The design of syndemic studies is another element suffering from a lack of diversity. The field is dominated by quantitative studies as qualitative papers represent only `r percent(.N_qual/nrow(overview_of_studies))` of our sample. Moreover `r percent(.N_cross_sec/nrow(summary_quantitative))` of the quantitative studies were cross-sectional. As vulnerability to syndemic conditions is suspected to arise from early adverse experience [@stall2007] longitudinal studies running over a long period of time are probably needed to study syndemic production among MSM.

Moreover, as shown in our result, qualitative papers are more prone to discuss the potential interactions between syndemic conditions. Some concepts and experiences needed to understand syndemic production in MSM can only be studied through a qualitative approach. For example, the complex narratives surrounding drug use and its link to loneliness, marginalisation, personal affirmation, resistance and lack of meaningful emotional connections [@Pollard2018a] would be hard to measure and model using quantitative data. As Tsai previously pointed out, the inevitable simplification needed to estimate statistical models may lead to an oversimplification of disease dynamics[@Tsai2018a]. Mixed methods studies are needed to complement robust statistical estimation with insights on sociocultural mechanisms and on the lived experiences of people facing this clustering of adverse conditions. Our review only identified `r max(year_design$cumulative[year_design$design == "Mixed"])` studies employing such mixed methodology. Future research would benefit from generating and analysing qualitative data to support and enrich their quantitative findings.

Finally, we identified `r .N_int` interventional studies with mixed results. The efficacy of interventions that target interconnected syndemic conditions is supported by a meta-analysis [@Pantalone2020], indicating that syndemic-based interventions hold promise for improving the health of marginalised populations. Nonetheless, the mixed results presented in our review probably reflect the current shallowness of our understanding of how syndemics operate in different populations across the globe. Therefore, we should strive to close this knowledge gap in order to improve the design of future interventions. However, we do not recommend researchers wait before designing and testing syndemic-based interventions as such interventions may also contribute to our understanding of disease interactions. In this regard, we share the view of Stall et al. in their response to Tsai's review [@Stall2015a]. Given the harms caused to marginalised populations by a syndemic, we also agree with them when they state that"[w]e cannot wait until the methodological question of interaction is settled to develop interventions to address these co-morbidities within high risk populations.' Nonetheless only two interventions were conducted since this commentary was written seven years ago and we have made little progress in our understanding of disease interaction. This indicates an urgent need to move the field forward, both towards the comprehension of disease interaction and towards intervention development and implementation.

## Subpopulations

Studying the health of MSM poses a challenge regarding the diversity of this population. While nearly half of the studies included in our sample studied a subpopulation of MSM, the number of MSM subpopulations is such that most MSM subpopulations remain underserved. For example, Young Black MSM are specifically studied in `r .N_YBMSM` studies while representing 52% of the new HIV diagnosis among MSM aged 13--24 years in 2018 [@centerfordiseasecontrolandprevention2020].

This discrepancy between the number of studies focusing on a subpopulation and the very high prevalence of some syndemic conditions such as HIV infection is even more concerning when considering that dual-minority identity may expose a person to different stressors and outcomes. For example, some studies found that Black MSM had a higher rate of HIV seroconversion than White MSM while being exposed to fewer syndemic conditions [@Mustanski2017]. These findings are supported by qualitative data suggesting that intersectional theory offers the context needed to understand syndemics among Black MSM which differ from syndemics among White MSM [@Quinn]. Furthermore, the findings from Bulled suggest that structural disadvantage may have more weight on the lives of Black MSM than individual factors such as substance use [@bulled2021]. We agree with the views of these authors and believe that more attention should be given to structural disadvantages such as institutional racism and how it impacts the emergence of different syndemic conditions.

MSMW are another example of an underserved population with conflicting results. In a cross-sectional study using syndemic sum count, Latino MSMW with two or more syndemic conditions had a 7.09 Odds Ratio to engage in receptive condomless anal sex but no statistically significant difference was found for insertive condomless anal sex or condomless vaginal sex [@Munoz-Laboy2018]. On the other hand, in another study the number of syndemic conditions was associated with HIV diagnosis for MSM but not for MSW or MSMW [@Branstrom2018]. Among young MSM and MSMW, one study found more syndemic conditions and a greater association between them for MSMW compared to MSM [@Mustanski2014]. On the contrary, Ferlatte et al. found that MSM were more likely than MSMW to suffer from two or more syndemic conditions [@ferlatte2018]. These conflicting findings may be partly due to the difficulty to define and operate bisexuality in research [@swan2018], differences between age groups or differences in syndemic mechanism for MSMW compared to MSM. Outside the field of syndemic literature, studies suggest that bisexual men suffer from a similar or higher burden of mental health conditions compared to gay men [@salway2019; @Chaudhry2019; @ross2018] and literature specific to bisexual men remains scarce. In the future, syndemic theory should thus seek to study the specificity of this population. First, there is a need to better conceptualise and define bisexuality in the field - should we still use solely a behaviour-based definition (as in MSMW) or should we incorporate a self-definition of one's sexual orientation? Then, researchers should aim to disaggregate data concerning MSMW/bisexual men from data concerning MSM/gay men whenever possible. Lastly, more research focusing on MSMW/bisexual men is needed.

Finally, transgender MSM were included in only one study in our sample. As stated in our results, this is concerning, especially when every other study excludes transgender men by design. As such, this population of MSM is the one we know the least about. It is striking that the number of studies we had to exclude due to merging transgender women and MSM was higher than the number of eligible studies found focusing on transgender men. This conflation of sex and gender has already been decried [@poteat2016] and contributed to our decision to exclude studies that reproduced this unfortunate practice. Linking transgender women and MSM on the assumption of shared biology and practices reduces transgender women to their birth assignation rather than their social identities. Conversely, excluding transgender MSM although they seem exposed to similar risk patterns as cisgender MSM [@Reisner2016a] because of their biological sex is, at best, revealing of a lack of knowledge about this population. Indeed, it seems counterproductive to give such precedent to the biological sex of participants over their social identifies while using a framework that considers diseases as socially caused. We believe that this practice is due to cissexist bias that should be avoided in future research.\
The health of transgender men remains greatly understudied and the few available studies suggest high rates of adverse conditions such as violence, notably sexual violence [@Testa2012], suicide attempts [@Haas2014], chlamydia and gonococcal infections [@Pitasi2019], intimate partner violence [@peitzmeier2020] and HIV infection [@Becasen2019]. Syndemic theory represents a promising framework for research on transgender men as its premises of social adversities producing and concentrating diseases in a population allows us to explore the health of transgender men without pathologising them.

## Syndemic conditions

There is a lack of consensus concerning the choice of syndemic conditions and the way they should be measured. We identified `r nrow(nodes)` different conditions in our quantitative sample, `r nrow(nodes %>% filter(studies == 1))` of them were only studied once. Despite this diversity of syndemic conditions, the impact of the seminal study by Stall et al. [@Stall2003] is striking. The conditions studied in that paper (depression, IPV, CSA and polysubstance use) are among the five most studied conditions in the field. Furthermore, `r percent(nrow(.Stall_conditions)/nrow(summary_quantitative))` of the quantitative studies included in our review consider at least one of the four conditions studied by Stall and colleagues as part of a syndemic.

Some of these conditions are past events (e.g. history of trauma or childhood sexual abuse) while most were current conditions. Given the cross-sectional nature of `r percent(.N_cross_sec/nrow(summary_quantitative))` of the quantitative papers, we cannot disentangle how past experiences may influence the emergence of a syndemic.

Furthermore, studies diverge on what represents a syndemic condition and what may lead to the emergence of a syndemic. For example, childhood sexual abuse is mostly seen as a syndemic condition per se but may very well be a risk factor to the emergence of a syndemic, as hypothesised by some authors [@Herrick2013; @leblanc2021]. The same question may be asked for other conditions, including discrimination, trauma, impulsivity, bullying, poor social support, loneliness, childhood abuse, or poor access to healthcare.\
Qualitative studies may help to distinguish between syndemic conditions and pathways to the emergence of a syndemic by drawing insights from the narratives of MSM. Life-story interviews, for example, offer the opportunity to explore how early challenges shaped the narratives and lives of individuals. Adam et al. conducted one such investigation and found one major pathway of syndemic production characterised by childhood adversity leading to depression, substance abuse and risk taking [@adam2018]. Two minor pathways characterised by migration stress, or transition stress from home to college/work were also described. These findings are in line with Stall's theory of syndemic production in which early socially produced harms, beginning in childhood, continue through adolescence and adult life and are aggravated by the stresses associated with migration to large urban centres [@stall2007]. Given that the childhood damages are socially produced, the experiences that produce a syndemic may differ across generations or subpopulations of MSM [@stall2007]. As such, it may be possible that one condition, such as poor social support, participates in the emergence of a syndemic in a subpopulation of MSM while being part of a syndemic in another. As this theory is first and foremost a developmental theory of syndemic production, longitudinal studies may also help to disentangle pathways and syndemic conditions by surveying participants over an extended period of time. However, conflating the two in cross-sectional studies does very little to advance our understanding of syndemic theory or to contribute to the implementation of public health interventions.

Furthermore, even when the same condition was studied in multiple papers, the differences in measurement methods impede the reproducibility of the results. For example, let's imagine a survivor of sexual intimate partner violence with a CESD score of 16, who uses marijuana on a regular basis and cocaine occasionally. This man would have been classified as depressed in `r percent(sum(.depression_measurement$depression_cutoff == 16 & .depression_measurement$depression_scale_criteria == "CESD", na.rm = T)/sum(.depression_measurement$depression_scale_criteria == "CESD"))` of studies using the CESD, a polysubstance user in `r percent(sum(.polysubstance_measurement$polysubstance_number == "More than one category of substance use" & .polysubstance_measurement$polysubstance_marijuana == "Marijuana included")/nrow(.polysubstance_measurement))` of studies considering polysubstance use and as a survivor of intimate partner violence in `r .IPV_prevalence$perc[["sexual IPV"]]` of studies considering IPV. In other words, the same person could have been classified as having zero, one, two or even three syndemic conditions, depending on the study design. Considering that most studies use a summation score of the number of syndemic conditions to conduct regression analysis, it seems evident that the results would vary greatly according to the way the syndemic conditions are measured.

It is beyond the scope of this paper to provide an exhaustive list of syndemic conditions researchers should use from now on or to determine the best scale or set of criteria to use to measure these conditions. An absolute answer to these questions is likely unrealistic due to variations across subpopulations and geographical settings.\
However, we advise researchers to pay more attention to the local context and the lived experience of the population they seek to study when selecting syndemic conditions to investigate. Focus groups or Delphi studies interrogating peer navigators of grassroots organisation serving MSM may help to select more pertinent variables. Indeed, by drawing on their own experiences and knowledge of the public they work with on a daily basis, peer navigators may help researchers ground their research more effectively.\
Additionally, exploratory qualitative studies may also serve as a first step in describing a syndemic arrangement before selecting syndemic conditions for a quantitative study. As Singer et al. stated in their 2020 paper:'[t]he syndemic relationship first needs to be observed then measured, not theorised and used to predict diseases outcomes [...]' [@Singer2020].

## Outcomes

Taken together, `r percent(.HIV_number/nrow(summary_quantitative))` of the quantitative studies in our sample had an HIV-related outcome, whether in the form of sexual risk behaviours, HIV diagnosis, HIV screening, adherence to antiretroviral therapy, PrEP use, viral load or engagement in HIV care.

This omnipresence of HIV in syndemic literature applied to MSM is understandable. The first description of a syndemic, the SAVA syndemic, included AIDS as part of a syndemic [@singer1996]. Then, a few years later, the first paper on syndemic in the MSM population had HIV-related outcomes, in the form of HIV serostatus and CAS [@Stall2003]. Furthermore, MSM were the first and most severely affected population when the AIDS epidemic started [@decock2012]. Nowadays, male-to-male sexual contact still represents nearly 70% of the new HIV cases in the USA [@centerfordiseasecontrolandprevention2020]. While we can't deny the importance of the HIV pandemic, notably for MSM, and especially in the Global South, where more research on syndemics and HIV is needed, we would argue that HIV is not the only issue in need of attention.

Indeed, MSM are also disproportionately affected by, among others, suicide, anxiety, depression and substance use [@ross2018; @luo2017; @Medley2016]. Moreover, with the advances in antiretroviral therapy and the subsequent decline in HIV-related mortality, a Canadian study showed that gay men were more likely to die from suicide than from HIV in 2011 [@hottes2015]. Even if the estimates presented in Hottes' paper overestimate the mortality due to suicide among MSM, suicide would still be a leading cause of death in this population while being studied as an outcome in only `r sum(!is.na(.outcomes$outcome_suicide))` papers in our sample.

Furthermore, when studying HIV as an outcome, we would argue that using condomless anal sex as a proxy should be reviewed, and better proxies sought. Indeed, condomless anal sex was one of the criteria in `r .CAS_number` studies out of the `r sum(!is.na(.outcomes$outcome_sexual_risk))` with sexual risk behaviours as an outcome and `r sum(!is.na(.outcomes_sex_risk_measurement$outcome_CAS))` studies considered all forms of condomless anal sex as a risk behaviour. However, without refinement, this outcome fails to capture the changes in HIV prevention strategies such as PrEP or Treatment as Prevention (TasP). Only `r english(sum(!is.na(.outcomes_sex_risk_measurement$outcome_PrEP_VL_CAS))+sum(!is.na(.outcomes_sex_risk_measurement$outcome_PrEP_CAS)))` studies in our sample took PrEP use and/or an undetectable viral load into account when considering condomless anal sex as a risk factor for HIV acquisition. Moreover, of these papers the oldest was published in 2019 [@Batchelder2019] although the FDA has approved PrEP for HIV prevention in 2012.\
When the first paper on syndemic theory applied to MSM was published, engaging in condomless anal sex would have led to a high risk of acquiring HIV. Nowadays, people could be on PrEP, forego the use of a condom and still be at a very low risk of acquiring HIV [@calabrese2017]. Our methodologies in syndemic research should reflect this evolution. In addition, qualitative research gives an insight into risk behaviours and offers a more nuanced view on this topic than a binary variable of consistent condom use for anal intercourse. One such paper published in 2017 showed that risk practices fell into different subjectivities such as active and consistent pursuit of condomless sex, lack of assertiveness to a partner's initiative of condomless anal sex and combination of episodic risk practices and reduction strategies [@Adam2017]. Besides, some studies showed that participants with a greater number of syndemic conditions would engage more frequently in condomless anal sex while not being more likely to test positive for HIV [@Mustanski2017; @Pitpitan2016]. On the other hand, a paper from 2018 found that having a greater number of syndemic conditions was associated with self-reported HIV but not to condomless anal sex [@chuang2018]. Taken together, we thus postulate that condomless anal sex should at least be replaced by "condomless anal sex without consistent PrEP use or with a detectable viral load" when an investigator seeks to use sexual risk behaviours as an outcome.

## Statistics and interaction

One of the tenets of syndemic theory is that there exists some form of biological, social and/or psychological interaction between the diseases [@mendenhall2020]. As others have already pointed out, the extent to which syndemic literature had proved this core principle remains very limited [@tsai2015]. Indeed, `r percent(.score_data/nrow(summary_quantitative))` of our quantitative sample of studies used solely a summation score of the syndemic conditions to conduct regression analysis. Two issues arise from this statistical approach. First, summation scores are additive by essence, thus unsuitable to demonstrate an interaction [@tsai2015]. Second, two psychometric assumptions are made by such a model: (1) the unidimensionality of the construct and (2) equal factor weighting [@Halkitis2013a]. Put simply, using a summation score would imply that (1) every condition forms a single construct and that (2) every condition contributes equally to said construct (which would mean for example that feeling depressed during the past 14 days and having a history of childhood sexual abuse would contribute equally to a syndemic). The unidimensionality aspect of the construct has received some empirical support by Mustanski et al. as well as by Starks et al. using respectively Structural Equation Modelling and Latent Class Analysis [@Mustanski2014; @Starks2014]. On the contrary, Leblanc et al. failed to construct a single latent syndemic variable in their analysis [@leblanc2021]. Moreover, constraining factor loadings to be equal resulted in worse fit in the studies by Mustanski and Starks.

In short, the result of our review suggests that as much as `r percent(.score_data/nrow(summary_quantitative))` of the quantitative literature on syndemic theory applied to MSM doesn't empirically support the presence of a syndemic and employs questionable statistical assumptions. Those studies are more an exploration of psychosocial risk factors associated with HIV acquisition or progression than the holistic framework syndemic is supposed to be.

As mentioned in the results, two statistically distinct models may be envisioned apart from synergistically interacting epidemics: mutually causal epidemics and serially causal epidemics [@Tsai2018a]. As such, mediation analysis, path analysis or structural equation modelling may prove useful to assess an interaction.

More recently, a new statistical approach inspired from research in psychopathology has been used to model syndemics: network analysis [@Lee; @lee2020]. The core principle of this approach is that mental disorders arise from causal interactions between symptoms in a network [@borsboom2017]. Applied to syndemic theory, a syndemic would then be the network and the various conditions would then be the nodes of the network. Furthermore, one of the benefits of this approach resides in the theoretical possibility to identify influential nodes in a network: nodes that play a significant part in the activation of the network and that could be the prime target of an intervention in order to deactivate the network [@robinaugh2016]. In short, in addition to being statistically sound and coherent with the model of mutually causal epidemics, network analysis could offer actionable data to improve the health of MSM by identifying which conditions should be prioritised for interventions [@Tsai2018a].

We recommend that future research should abandon the summation score approach and attempt to clarify which model of interaction receives the most empirical support in order to implement effective public health interventions. Indeed, as reminded by Chakrapani et al., the three models have different programmatic implications [@Chakrapani2019]. In the case of synergistically interacting epidemics, a single intervention may yield greater health improvement than if no interaction was present. For mutually causal epidemics, multicomponent interventions addressing the various epidemics should be implemented in order to produce an improvement. Finally, for serially causal epidemics, intervening at the root cause of a syndemic may prevent the development of a syndemic cascade.

## Additional frameworks

Resilience theory was the most frequently used framework to compliment syndemic theory.

Social support was shown to moderate the effect of syndemic conditions on viral load, providing a significant protective effect [@friedman2016]. Moreover, a paper using Latent Transition Analysis to evaluate the impact of syndemic conditions on substance use showed that Black MSM with more social support were more likely to stay in the low-risk class or transitioning from the high-risk class to the low-risk class [@turpin2020]. However, Chakrapani et al. found no moderation of social support on the relationship between syndemic conditions and risk taking [@Chakrapani2017].

On the topic of resilience resources, Zhang et al. did not find evidence of a moderating effect of resilience on the relationship between syndemic conditions and physical activity [@Zhang2019]. O'Leary et al. did not find a buffering effect of resilience factors on the relationship between syndemic conditions and sexual risk behaviours, though optimism and education buffered the relationship between syndemic conditions and self-reported HIV status [@OLeary2014a]. On the other hand, Kurtz et al. found that, among MSM living with HIV, serosorting was positively associated with higher levels of two resilience factors: coping self-efficacy and positive coping skills [@Kurtz2012]. Similarly, Hart et al. found that psychosocial strengths were associated with lower likelihood of engaging in condomless anal sex, despite the presence of syndemic conditions [@Hart2017].

In qualitative studies, resilience was also found to exert a protective effect against syndemic conditions [@Chakrapani2019a; @Reed2016; @adam2018]. Furthermore, the review by Woodwards et al. found a protective effect of most resilience resources identified against HIV [@woodward2017]. Additionally, as pointed out by Namer and Razum, focusing on risk rather than resilience and survivorship poses the threat of alienating minority groups rather than prioritising them [@namer2021].

Minority stress represents another important framework as it explains how social stigma can get under the skin of minorised populations [@Meyer2003]. Indeed, minority stress is fully integrated into theories of syndemic production among MSM [@stall2007; @singer2017]. In these theories, the minority stress experienced by MSM leads to maladaptive coping strategies such as substance abuse, development of psychopathological conditions such as anxiety disorders and depression, hereby increasing sexual risk behaviours. Therefore, minority stress theory offers a mechanistic explanation of the second tenet of syndemic theory: the formation and clustering of diseases due to adverse social conditions.\
As we recommend that future research better incorporate mental health issues, we believe that minority stress theory could be more often integrated into future analysis.\
Additionally, another advantage of minority stress theory is that it avoids pathologising MSM by placing the focus on the social roots of mental health issues.

Finally, although intersectionality was only used by two studies [@ferlatte2018; @Quinn], we believe the field would benefit from this framework. Indeed, as shown in our results, there is some discrepancy in the results for subpopulations of MSM, especially for MSMW/bisexual men, Black MSM and Latino MSM. We believe that the inattention to systemic inequalities and structural disadvantage in the field may partly explain these discrepancies. In fact, only `r percent((summary_quantitative %>% filter(!is.na(unstable_housing) | !is.na(discrimination) | !is.na(incarceration) | !is.na(poverty)| !is.na (unemployment) | !is.na(healthcare_access)) %>% nrow())/nrow(summary_quantitative))` of the quantitative studies examine a structural condition such as discrimination, poverty or access to healthcare. However, as Bulled et al. reminds us, one of the goals of the syndemic framework is to "identify the role of power and structural injustices in creating pathology and recognising how pathology can intensify inequalities and multiple forms of oppression" [@bulled2022].

Some scholars are sceptical of the usefulness of syndemic theory to intersectionality and question the possibility of a conversation between the two fields [@sangaramoorthy2021]. As pertinent as the authors' commentary is, we do believe in the possibility of bringing the two fields together. As Quinn pointed out in her response, incorporating an intersectional framework into syndemic research may address issues of power, oppression and structural violence, neglected thus far in the field [@quinn2021]. Doing so, we may address some gaps in the literature and disentangle the complex web of stigma and structural violence faced by sexual minority men, especially MSM situated at the intersection of multiple form of systemic discrimination such as racism, homophobia, biphobia, transphobia, classism, ableism or stigma against sex workers or people living with HIV. Furthermore, we agree with Bulled et al. when they argue that we need a syndemic analysis to understand clustering of diseases in marginalised populations [@bulled2022] . Moreover, given the results of this review, we share the opinion that most of the criticism from Sangaramoorthy and Benton stems from flaws in the way research in the field was conducted rather than flaws in the framework itself.

## Recommendations

In light of these results, we propose the following suggestions to improve the quality of research on syndemic theory applied to MSM:

1.  The local context should be taken into consideration more effectively by scholars. Analysis of the physical space through spatial epidemiology should be encouraged while merging data from different states and countries should be avoided as it blurs our understanding of the socioeconomic and cultural contexts in which MSM evolve.

2.  More research should be conducted in the Global South, taking into account the difficulties involved when transposing some measures to different sociocultural contexts.

3.  Researchers should carefully select syndemic conditions to avoid unnecessary dispersion and to select the most relevant variables to MSM in a given place at a given time. Exploratory qualitative research, focus groups or Delphi survey should be used before trying to quantify a syndemic.

4.  More attention should be paid to the selection of scales or sets of criteria when attempting to measure a syndemic condition to improve the reproducibility of the results.

5.  A better understanding of how diseases interact is urgently needed. First, future research should abandon the summation score approach and aim to determine the model of interaction with the most empirical support. Second, future research should elucidate the mechanisms of bio-social and bio-bio interactions. Qualitative and mixed method studies should be employed more often to achieve this.

6.  More attention should be given to structural disadvantage and systemic inequalities such as racism, biphobia, and transphobia in order to gain a better insight into racial disparities in syndemic production. Furthermore, the impact of monosexism and cissexism on the health of MSM should become a topic of investigation.

7.  Transgender men should be included in the population of MSM in future studies, rather than conflating sex and gender by excluding them while often including transgender women alongside MSM. Moreover, whenever possible, data from MSMW should be disaggregated to allow in-depth analysis.

8.  Researchers should seek to study other aspects of MSM's health than HIV infection. Mental health should no longer be neglected anymore. Moreover, when studying HIV infection, the outcome condomless anal sex should be replaced or refined.

9.  Future work should continue to explore the impact of resilience in partially counteracting syndemics to develop public health interventions that aim to foster resilience resources among MSM.
