# Strengths and limitations

This review is the first Scoping Review to map the current knowledge in Syndemic Theory applied to MSM. We charted and presented detailed data regarding the way research has been done. As such, we offer a precious insight and actionable recommendations for the future of the field. Our search strategy of electronic databases was comprehensive and developed with the help of the director of health sciences library of our institution. We combined this database search with a secondary hand-search of references lists of the included studies. Moreover, we conducted a fully transparent and reproducible review. Other researchers may freely reuse our data and scripts to conduct their own work or use our database to identify papers pertinent for their research projects.

Nevertheless, even though we took several steps to ensure the comprehensiveness of our search strategy, we may still have missed some relevant literature. Furthermore, one of our inclusion criteria was the centrality of syndemic theory to the screened paper. Although two reviewers screened a part of the studies independently, this criteria may be somewhat arbitrary and other researchers may have chosen to include papers we rejected or the contrary. Finally, the usual limitations of a scoping review apply such as the lack of risk of bias and strength of evidence assessment.

# Conclusion and recommendations

Our review of syndemic research applied to MSM revealed some important limitations that must be addressed in future work. The field of syndemic research would benefit from studying more MSM subpopulations, in more diverse geographical settings, especially in the Global South. Furthermore, promising methods such as spatial epidemiology or network analysis may help to advance the field while methods such as summary count should be abandoned. More qualitative and mixed design may enhance our understanding of the complex interactions of a syndemic on the lived experiences of marginalized people. Outcomes should be less focused on sexual health and start to explore other potential impacts of a syndemic on health. Finally, conditions that constitute a syndemic should be more precisely defined and the measurement of those conditions should be more standardized while taking into account the difficulties of transposing some measures in different sociocultural contexts.

Despite our critical stance on the current literature, we remained convinced that syndemic is a useful framework to study the health of marginalized populations in a holistic way and the current research still offered valuable insights on the health of MSM. It is vital that research continues to evolve in order to deepen our understanding and, by consequence, improve the health of marginalized populations worldwide.

# Funding

We did not receive any specific grant for this research from any funding agency in the public, commercial or not-for-profit sectors.
